name: Mirror Sync




on:
  workflow_dispatch: 
#  schedule:
#    - cron: "0 * * * *"








permissions:
  contents: write




jobs:




  build:




    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0']
        




    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Generate README
      run: |
        bundle exec $GITHUB_WORKSPACE/scripts/generate-readme < README.md.erb > README.md
    - name: Download Blacklist
      run: |
        curl -O http://dsi.ut-capitole.fr/blacklists/download/blacklists.tar.gz
    - name: Repacking
      run: |
        rm -r blacklists
        tar -xf blacklists.tar.gz
        find blacklists -type f -size +99M -exec gzip -nf {} \;
        rm blacklists.tar.gz
    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Mirror Sync"
        git push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
