name: Mirror Sync




on:
  workflow_dispatch: 
#  schedule:
#    - cron: "0 * * * *"








permissions:
  contents: write




jobs:




  build:




    runs-on: ubuntu-latest




    steps:
    - uses: actions/checkout@v4
    - name: Download Blacklist
      run: |
        curl -O http://dsi.ut-capitole.fr/blacklists/download/blacklists.tar.gz
    - name: Repacking
      run: |
        rm -r blacklists
        tar -xf blacklists.tar.gz
        find blacklists -type f -size +99M -exec gzip -nf {} \;
        rm blacklists.tar.gz
    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Mirror Sync"
        git push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
